//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSFTechSoapDemo.WSFTech {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="response_ws", Namespace="http://webservice.facturatech.co/")]
    [System.SerializableAttribute()]
    public partial class response_ws : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string successField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transaccionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgerrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string success {
            get {
                return this.successField;
            }
            set {
                if ((object.ReferenceEquals(this.successField, value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string transaccionID {
            get {
                return this.transaccionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.transaccionIDField, value) != true)) {
                    this.transaccionIDField = value;
                    this.RaisePropertyChanged("transaccionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Msgerror {
            get {
                return this.MsgerrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgerrorField, value) != true)) {
                    this.MsgerrorField = value;
                    this.RaisePropertyChanged("Msgerror");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="response_docs", Namespace="http://webservice.facturatech.co/")]
    [System.SerializableAttribute()]
    public partial class response_docs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string successField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgerrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string success {
            get {
                return this.successField;
            }
            set {
                if ((object.ReferenceEquals(this.successField, value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Msgerror {
            get {
                return this.MsgerrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgerrorField, value) != true)) {
                    this.MsgerrorField = value;
                    this.RaisePropertyChanged("Msgerror");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="response_xml", Namespace="http://webservice.facturatech.co/")]
    [System.SerializableAttribute()]
    public partial class response_xml : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string successField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resourceDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgerrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string success {
            get {
                return this.successField;
            }
            set {
                if ((object.ReferenceEquals(this.successField, value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string resourceData {
            get {
                return this.resourceDataField;
            }
            set {
                if ((object.ReferenceEquals(this.resourceDataField, value) != true)) {
                    this.resourceDataField = value;
                    this.RaisePropertyChanged("resourceData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Msgerror {
            get {
                return this.MsgerrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgerrorField, value) != true)) {
                    this.MsgerrorField = value;
                    this.RaisePropertyChanged("Msgerror");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="response_pdf", Namespace="http://webservice.facturatech.co/")]
    [System.SerializableAttribute()]
    public partial class response_pdf : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string successField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resourceDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgerrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string success {
            get {
                return this.successField;
            }
            set {
                if ((object.ReferenceEquals(this.successField, value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string resourceData {
            get {
                return this.resourceDataField;
            }
            set {
                if ((object.ReferenceEquals(this.resourceDataField, value) != true)) {
                    this.resourceDataField = value;
                    this.RaisePropertyChanged("resourceData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Msgerror {
            get {
                return this.MsgerrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgerrorField, value) != true)) {
                    this.MsgerrorField = value;
                    this.RaisePropertyChanged("Msgerror");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="response_cufe", Namespace="http://webservice.facturatech.co/")]
    [System.SerializableAttribute()]
    public partial class response_cufe : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string successField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resourceDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgerrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string success {
            get {
                return this.successField;
            }
            set {
                if ((object.ReferenceEquals(this.successField, value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string resourceData {
            get {
                return this.resourceDataField;
            }
            set {
                if ((object.ReferenceEquals(this.resourceDataField, value) != true)) {
                    this.resourceDataField = value;
                    this.RaisePropertyChanged("resourceData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Msgerror {
            get {
                return this.MsgerrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgerrorField, value) != true)) {
                    this.MsgerrorField = value;
                    this.RaisePropertyChanged("Msgerror");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="response_qr", Namespace="http://webservice.facturatech.co/")]
    [System.SerializableAttribute()]
    public partial class response_qr : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string successField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resourceDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgerrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string success {
            get {
                return this.successField;
            }
            set {
                if ((object.ReferenceEquals(this.successField, value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string resourceData {
            get {
                return this.resourceDataField;
            }
            set {
                if ((object.ReferenceEquals(this.resourceDataField, value) != true)) {
                    this.resourceDataField = value;
                    this.RaisePropertyChanged("resourceData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Msgerror {
            get {
                return this.MsgerrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgerrorField, value) != true)) {
                    this.MsgerrorField = value;
                    this.RaisePropertyChanged("Msgerror");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="response_qr_image_file", Namespace="http://webservice.facturatech.co/")]
    [System.SerializableAttribute()]
    public partial class response_qr_image_file : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string successField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resourceDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgerrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string success {
            get {
                return this.successField;
            }
            set {
                if ((object.ReferenceEquals(this.successField, value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string resourceData {
            get {
                return this.resourceDataField;
            }
            set {
                if ((object.ReferenceEquals(this.resourceDataField, value) != true)) {
                    this.resourceDataField = value;
                    this.RaisePropertyChanged("resourceData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Msgerror {
            get {
                return this.MsgerrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgerrorField, value) != true)) {
                    this.MsgerrorField = value;
                    this.RaisePropertyChanged("Msgerror");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.facturatech.co/", ConfigurationName="WSFTech.WSV2DEMOSoap")]
    public interface WSV2DEMOSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://webservice.facturatech.co/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/uploadInvoiceFile", ReplyAction="*")]
        WSFTechSoapDemo.WSFTech.uploadInvoiceFileResponse uploadInvoiceFile(WSFTechSoapDemo.WSFTech.uploadInvoiceFileRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://webservice.facturatech.co/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/uploadInvoiceFileLayout", ReplyAction="*")]
        WSFTechSoapDemo.WSFTech.uploadInvoiceFileLayoutResponse uploadInvoiceFileLayout(WSFTechSoapDemo.WSFTech.uploadInvoiceFileLayoutRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://webservice.facturatech.co/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/documentStatusFile", ReplyAction="*")]
        WSFTechSoapDemo.WSFTech.documentStatusFileResponse documentStatusFile(WSFTechSoapDemo.WSFTech.documentStatusFileRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://webservice.facturatech.co/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/downloadXMLFile", ReplyAction="*")]
        WSFTechSoapDemo.WSFTech.downloadXMLFileResponse downloadXMLFile(WSFTechSoapDemo.WSFTech.downloadXMLFileRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://webservice.facturatech.co/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/downloadPDFFile", ReplyAction="*")]
        WSFTechSoapDemo.WSFTech.downloadPDFFileResponse downloadPDFFile(WSFTechSoapDemo.WSFTech.downloadPDFFileRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://webservice.facturatech.co/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/downloadCUFEFile", ReplyAction="*")]
        WSFTechSoapDemo.WSFTech.downloadCUFEFileResponse downloadCUFEFile(WSFTechSoapDemo.WSFTech.downloadCUFEFileRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://webservice.facturatech.co/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/downloadQRFile", ReplyAction="*")]
        WSFTechSoapDemo.WSFTech.downloadQRFileResponse downloadQRFile(WSFTechSoapDemo.WSFTech.downloadQRFileRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://webservice.facturatech.co/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/downloadQRImageFile", ReplyAction="*")]
        WSFTechSoapDemo.WSFTech.downloadQRImageFileResponse downloadQRImageFile(WSFTechSoapDemo.WSFTech.downloadQRImageFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadInvoiceFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="uploadInvoiceFile", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapDemo.WSFTech.uploadInvoiceFileRequestBody Body;
        
        public uploadInvoiceFileRequest() {
        }
        
        public uploadInvoiceFileRequest(WSFTechSoapDemo.WSFTech.uploadInvoiceFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class uploadInvoiceFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xmlBase64;
        
        public uploadInvoiceFileRequestBody() {
        }
        
        public uploadInvoiceFileRequestBody(string username, string password, string xmlBase64) {
            this.username = username;
            this.password = password;
            this.xmlBase64 = xmlBase64;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadInvoiceFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="uploadInvoiceFileResponse", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapDemo.WSFTech.uploadInvoiceFileResponseBody Body;
        
        public uploadInvoiceFileResponse() {
        }
        
        public uploadInvoiceFileResponse(WSFTechSoapDemo.WSFTech.uploadInvoiceFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class uploadInvoiceFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSFTechSoapDemo.WSFTech.response_ws uploadInvoiceFileResult;
        
        public uploadInvoiceFileResponseBody() {
        }
        
        public uploadInvoiceFileResponseBody(WSFTechSoapDemo.WSFTech.response_ws uploadInvoiceFileResult) {
            this.uploadInvoiceFileResult = uploadInvoiceFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadInvoiceFileLayoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="uploadInvoiceFileLayout", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapDemo.WSFTech.uploadInvoiceFileLayoutRequestBody Body;
        
        public uploadInvoiceFileLayoutRequest() {
        }
        
        public uploadInvoiceFileLayoutRequest(WSFTechSoapDemo.WSFTech.uploadInvoiceFileLayoutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class uploadInvoiceFileLayoutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xmlBase64;
        
        public uploadInvoiceFileLayoutRequestBody() {
        }
        
        public uploadInvoiceFileLayoutRequestBody(string username, string password, string xmlBase64) {
            this.username = username;
            this.password = password;
            this.xmlBase64 = xmlBase64;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadInvoiceFileLayoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="uploadInvoiceFileLayoutResponse", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapDemo.WSFTech.uploadInvoiceFileLayoutResponseBody Body;
        
        public uploadInvoiceFileLayoutResponse() {
        }
        
        public uploadInvoiceFileLayoutResponse(WSFTechSoapDemo.WSFTech.uploadInvoiceFileLayoutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class uploadInvoiceFileLayoutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSFTechSoapDemo.WSFTech.response_ws uploadInvoiceFileLayoutResult;
        
        public uploadInvoiceFileLayoutResponseBody() {
        }
        
        public uploadInvoiceFileLayoutResponseBody(WSFTechSoapDemo.WSFTech.response_ws uploadInvoiceFileLayoutResult) {
            this.uploadInvoiceFileLayoutResult = uploadInvoiceFileLayoutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class documentStatusFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="documentStatusFile", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapDemo.WSFTech.documentStatusFileRequestBody Body;
        
        public documentStatusFileRequest() {
        }
        
        public documentStatusFileRequest(WSFTechSoapDemo.WSFTech.documentStatusFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class documentStatusFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string transaccionID;
        
        public documentStatusFileRequestBody() {
        }
        
        public documentStatusFileRequestBody(string username, string password, string transaccionID) {
            this.username = username;
            this.password = password;
            this.transaccionID = transaccionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class documentStatusFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="documentStatusFileResponse", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapDemo.WSFTech.documentStatusFileResponseBody Body;
        
        public documentStatusFileResponse() {
        }
        
        public documentStatusFileResponse(WSFTechSoapDemo.WSFTech.documentStatusFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class documentStatusFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSFTechSoapDemo.WSFTech.response_docs documentStatusFileResult;
        
        public documentStatusFileResponseBody() {
        }
        
        public documentStatusFileResponseBody(WSFTechSoapDemo.WSFTech.response_docs documentStatusFileResult) {
            this.documentStatusFileResult = documentStatusFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadXMLFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadXMLFile", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapDemo.WSFTech.downloadXMLFileRequestBody Body;
        
        public downloadXMLFileRequest() {
        }
        
        public downloadXMLFileRequest(WSFTechSoapDemo.WSFTech.downloadXMLFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class downloadXMLFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prefijo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string folio;
        
        public downloadXMLFileRequestBody() {
        }
        
        public downloadXMLFileRequestBody(string username, string password, string prefijo, string folio) {
            this.username = username;
            this.password = password;
            this.prefijo = prefijo;
            this.folio = folio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadXMLFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadXMLFileResponse", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapDemo.WSFTech.downloadXMLFileResponseBody Body;
        
        public downloadXMLFileResponse() {
        }
        
        public downloadXMLFileResponse(WSFTechSoapDemo.WSFTech.downloadXMLFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class downloadXMLFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSFTechSoapDemo.WSFTech.response_xml downloadXMLFileResult;
        
        public downloadXMLFileResponseBody() {
        }
        
        public downloadXMLFileResponseBody(WSFTechSoapDemo.WSFTech.response_xml downloadXMLFileResult) {
            this.downloadXMLFileResult = downloadXMLFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadPDFFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadPDFFile", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapDemo.WSFTech.downloadPDFFileRequestBody Body;
        
        public downloadPDFFileRequest() {
        }
        
        public downloadPDFFileRequest(WSFTechSoapDemo.WSFTech.downloadPDFFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class downloadPDFFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prefijo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string folio;
        
        public downloadPDFFileRequestBody() {
        }
        
        public downloadPDFFileRequestBody(string username, string password, string prefijo, string folio) {
            this.username = username;
            this.password = password;
            this.prefijo = prefijo;
            this.folio = folio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadPDFFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadPDFFileResponse", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapDemo.WSFTech.downloadPDFFileResponseBody Body;
        
        public downloadPDFFileResponse() {
        }
        
        public downloadPDFFileResponse(WSFTechSoapDemo.WSFTech.downloadPDFFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class downloadPDFFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSFTechSoapDemo.WSFTech.response_pdf downloadPDFFileResult;
        
        public downloadPDFFileResponseBody() {
        }
        
        public downloadPDFFileResponseBody(WSFTechSoapDemo.WSFTech.response_pdf downloadPDFFileResult) {
            this.downloadPDFFileResult = downloadPDFFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadCUFEFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadCUFEFile", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapDemo.WSFTech.downloadCUFEFileRequestBody Body;
        
        public downloadCUFEFileRequest() {
        }
        
        public downloadCUFEFileRequest(WSFTechSoapDemo.WSFTech.downloadCUFEFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class downloadCUFEFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prefijo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string folio;
        
        public downloadCUFEFileRequestBody() {
        }
        
        public downloadCUFEFileRequestBody(string username, string password, string prefijo, string folio) {
            this.username = username;
            this.password = password;
            this.prefijo = prefijo;
            this.folio = folio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadCUFEFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadCUFEFileResponse", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapDemo.WSFTech.downloadCUFEFileResponseBody Body;
        
        public downloadCUFEFileResponse() {
        }
        
        public downloadCUFEFileResponse(WSFTechSoapDemo.WSFTech.downloadCUFEFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class downloadCUFEFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSFTechSoapDemo.WSFTech.response_cufe downloadCUFEFileResult;
        
        public downloadCUFEFileResponseBody() {
        }
        
        public downloadCUFEFileResponseBody(WSFTechSoapDemo.WSFTech.response_cufe downloadCUFEFileResult) {
            this.downloadCUFEFileResult = downloadCUFEFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadQRFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadQRFile", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapDemo.WSFTech.downloadQRFileRequestBody Body;
        
        public downloadQRFileRequest() {
        }
        
        public downloadQRFileRequest(WSFTechSoapDemo.WSFTech.downloadQRFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class downloadQRFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prefijo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string folio;
        
        public downloadQRFileRequestBody() {
        }
        
        public downloadQRFileRequestBody(string username, string password, string prefijo, string folio) {
            this.username = username;
            this.password = password;
            this.prefijo = prefijo;
            this.folio = folio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadQRFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadQRFileResponse", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapDemo.WSFTech.downloadQRFileResponseBody Body;
        
        public downloadQRFileResponse() {
        }
        
        public downloadQRFileResponse(WSFTechSoapDemo.WSFTech.downloadQRFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class downloadQRFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSFTechSoapDemo.WSFTech.response_qr downloadQRFileResult;
        
        public downloadQRFileResponseBody() {
        }
        
        public downloadQRFileResponseBody(WSFTechSoapDemo.WSFTech.response_qr downloadQRFileResult) {
            this.downloadQRFileResult = downloadQRFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadQRImageFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadQRImageFile", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapDemo.WSFTech.downloadQRImageFileRequestBody Body;
        
        public downloadQRImageFileRequest() {
        }
        
        public downloadQRImageFileRequest(WSFTechSoapDemo.WSFTech.downloadQRImageFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class downloadQRImageFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prefijo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string folio;
        
        public downloadQRImageFileRequestBody() {
        }
        
        public downloadQRImageFileRequestBody(string username, string password, string prefijo, string folio) {
            this.username = username;
            this.password = password;
            this.prefijo = prefijo;
            this.folio = folio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadQRImageFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadQRImageFileResponse", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapDemo.WSFTech.downloadQRImageFileResponseBody Body;
        
        public downloadQRImageFileResponse() {
        }
        
        public downloadQRImageFileResponse(WSFTechSoapDemo.WSFTech.downloadQRImageFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class downloadQRImageFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSFTechSoapDemo.WSFTech.response_qr_image_file downloadQRImageFileResult;
        
        public downloadQRImageFileResponseBody() {
        }
        
        public downloadQRImageFileResponseBody(WSFTechSoapDemo.WSFTech.response_qr_image_file downloadQRImageFileResult) {
            this.downloadQRImageFileResult = downloadQRImageFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSV2DEMOSoapChannel : WSFTechSoapDemo.WSFTech.WSV2DEMOSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSV2DEMOSoapClient : System.ServiceModel.ClientBase<WSFTechSoapDemo.WSFTech.WSV2DEMOSoap>, WSFTechSoapDemo.WSFTech.WSV2DEMOSoap {
        
        public WSV2DEMOSoapClient() {
        }
        
        public WSV2DEMOSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSV2DEMOSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSV2DEMOSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSV2DEMOSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFTechSoapDemo.WSFTech.uploadInvoiceFileResponse WSFTechSoapDemo.WSFTech.WSV2DEMOSoap.uploadInvoiceFile(WSFTechSoapDemo.WSFTech.uploadInvoiceFileRequest request) {
            return base.Channel.uploadInvoiceFile(request);
        }
        
        public WSFTechSoapDemo.WSFTech.response_ws uploadInvoiceFile(string username, string password, string xmlBase64) {
            WSFTechSoapDemo.WSFTech.uploadInvoiceFileRequest inValue = new WSFTechSoapDemo.WSFTech.uploadInvoiceFileRequest();
            inValue.Body = new WSFTechSoapDemo.WSFTech.uploadInvoiceFileRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.xmlBase64 = xmlBase64;
            WSFTechSoapDemo.WSFTech.uploadInvoiceFileResponse retVal = ((WSFTechSoapDemo.WSFTech.WSV2DEMOSoap)(this)).uploadInvoiceFile(inValue);
            return retVal.Body.uploadInvoiceFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFTechSoapDemo.WSFTech.uploadInvoiceFileLayoutResponse WSFTechSoapDemo.WSFTech.WSV2DEMOSoap.uploadInvoiceFileLayout(WSFTechSoapDemo.WSFTech.uploadInvoiceFileLayoutRequest request) {
            return base.Channel.uploadInvoiceFileLayout(request);
        }
        
        public WSFTechSoapDemo.WSFTech.response_ws uploadInvoiceFileLayout(string username, string password, string xmlBase64) {
            WSFTechSoapDemo.WSFTech.uploadInvoiceFileLayoutRequest inValue = new WSFTechSoapDemo.WSFTech.uploadInvoiceFileLayoutRequest();
            inValue.Body = new WSFTechSoapDemo.WSFTech.uploadInvoiceFileLayoutRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.xmlBase64 = xmlBase64;
            WSFTechSoapDemo.WSFTech.uploadInvoiceFileLayoutResponse retVal = ((WSFTechSoapDemo.WSFTech.WSV2DEMOSoap)(this)).uploadInvoiceFileLayout(inValue);
            return retVal.Body.uploadInvoiceFileLayoutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFTechSoapDemo.WSFTech.documentStatusFileResponse WSFTechSoapDemo.WSFTech.WSV2DEMOSoap.documentStatusFile(WSFTechSoapDemo.WSFTech.documentStatusFileRequest request) {
            return base.Channel.documentStatusFile(request);
        }
        
        public WSFTechSoapDemo.WSFTech.response_docs documentStatusFile(string username, string password, string transaccionID) {
            WSFTechSoapDemo.WSFTech.documentStatusFileRequest inValue = new WSFTechSoapDemo.WSFTech.documentStatusFileRequest();
            inValue.Body = new WSFTechSoapDemo.WSFTech.documentStatusFileRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.transaccionID = transaccionID;
            WSFTechSoapDemo.WSFTech.documentStatusFileResponse retVal = ((WSFTechSoapDemo.WSFTech.WSV2DEMOSoap)(this)).documentStatusFile(inValue);
            return retVal.Body.documentStatusFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFTechSoapDemo.WSFTech.downloadXMLFileResponse WSFTechSoapDemo.WSFTech.WSV2DEMOSoap.downloadXMLFile(WSFTechSoapDemo.WSFTech.downloadXMLFileRequest request) {
            return base.Channel.downloadXMLFile(request);
        }
        
        public WSFTechSoapDemo.WSFTech.response_xml downloadXMLFile(string username, string password, string prefijo, string folio) {
            WSFTechSoapDemo.WSFTech.downloadXMLFileRequest inValue = new WSFTechSoapDemo.WSFTech.downloadXMLFileRequest();
            inValue.Body = new WSFTechSoapDemo.WSFTech.downloadXMLFileRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.prefijo = prefijo;
            inValue.Body.folio = folio;
            WSFTechSoapDemo.WSFTech.downloadXMLFileResponse retVal = ((WSFTechSoapDemo.WSFTech.WSV2DEMOSoap)(this)).downloadXMLFile(inValue);
            return retVal.Body.downloadXMLFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFTechSoapDemo.WSFTech.downloadPDFFileResponse WSFTechSoapDemo.WSFTech.WSV2DEMOSoap.downloadPDFFile(WSFTechSoapDemo.WSFTech.downloadPDFFileRequest request) {
            return base.Channel.downloadPDFFile(request);
        }
        
        public WSFTechSoapDemo.WSFTech.response_pdf downloadPDFFile(string username, string password, string prefijo, string folio) {
            WSFTechSoapDemo.WSFTech.downloadPDFFileRequest inValue = new WSFTechSoapDemo.WSFTech.downloadPDFFileRequest();
            inValue.Body = new WSFTechSoapDemo.WSFTech.downloadPDFFileRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.prefijo = prefijo;
            inValue.Body.folio = folio;
            WSFTechSoapDemo.WSFTech.downloadPDFFileResponse retVal = ((WSFTechSoapDemo.WSFTech.WSV2DEMOSoap)(this)).downloadPDFFile(inValue);
            return retVal.Body.downloadPDFFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFTechSoapDemo.WSFTech.downloadCUFEFileResponse WSFTechSoapDemo.WSFTech.WSV2DEMOSoap.downloadCUFEFile(WSFTechSoapDemo.WSFTech.downloadCUFEFileRequest request) {
            return base.Channel.downloadCUFEFile(request);
        }
        
        public WSFTechSoapDemo.WSFTech.response_cufe downloadCUFEFile(string username, string password, string prefijo, string folio) {
            WSFTechSoapDemo.WSFTech.downloadCUFEFileRequest inValue = new WSFTechSoapDemo.WSFTech.downloadCUFEFileRequest();
            inValue.Body = new WSFTechSoapDemo.WSFTech.downloadCUFEFileRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.prefijo = prefijo;
            inValue.Body.folio = folio;
            WSFTechSoapDemo.WSFTech.downloadCUFEFileResponse retVal = ((WSFTechSoapDemo.WSFTech.WSV2DEMOSoap)(this)).downloadCUFEFile(inValue);
            return retVal.Body.downloadCUFEFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFTechSoapDemo.WSFTech.downloadQRFileResponse WSFTechSoapDemo.WSFTech.WSV2DEMOSoap.downloadQRFile(WSFTechSoapDemo.WSFTech.downloadQRFileRequest request) {
            return base.Channel.downloadQRFile(request);
        }
        
        public WSFTechSoapDemo.WSFTech.response_qr downloadQRFile(string username, string password, string prefijo, string folio) {
            WSFTechSoapDemo.WSFTech.downloadQRFileRequest inValue = new WSFTechSoapDemo.WSFTech.downloadQRFileRequest();
            inValue.Body = new WSFTechSoapDemo.WSFTech.downloadQRFileRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.prefijo = prefijo;
            inValue.Body.folio = folio;
            WSFTechSoapDemo.WSFTech.downloadQRFileResponse retVal = ((WSFTechSoapDemo.WSFTech.WSV2DEMOSoap)(this)).downloadQRFile(inValue);
            return retVal.Body.downloadQRFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFTechSoapDemo.WSFTech.downloadQRImageFileResponse WSFTechSoapDemo.WSFTech.WSV2DEMOSoap.downloadQRImageFile(WSFTechSoapDemo.WSFTech.downloadQRImageFileRequest request) {
            return base.Channel.downloadQRImageFile(request);
        }
        
        public WSFTechSoapDemo.WSFTech.response_qr_image_file downloadQRImageFile(string username, string password, string prefijo, string folio) {
            WSFTechSoapDemo.WSFTech.downloadQRImageFileRequest inValue = new WSFTechSoapDemo.WSFTech.downloadQRImageFileRequest();
            inValue.Body = new WSFTechSoapDemo.WSFTech.downloadQRImageFileRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.prefijo = prefijo;
            inValue.Body.folio = folio;
            WSFTechSoapDemo.WSFTech.downloadQRImageFileResponse retVal = ((WSFTechSoapDemo.WSFTech.WSV2DEMOSoap)(this)).downloadQRImageFile(inValue);
            return retVal.Body.downloadQRImageFileResult;
        }
    }
}
