//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSFTechSoapPro.WSFTECHPRO {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="response_ws", Namespace="http://webservice.facturatech.co/")]
    [System.SerializableAttribute()]
    public partial class response_ws : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string successField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transaccionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgerrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string success {
            get {
                return this.successField;
            }
            set {
                if ((object.ReferenceEquals(this.successField, value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string transaccionID {
            get {
                return this.transaccionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.transaccionIDField, value) != true)) {
                    this.transaccionIDField = value;
                    this.RaisePropertyChanged("transaccionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Msgerror {
            get {
                return this.MsgerrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgerrorField, value) != true)) {
                    this.MsgerrorField = value;
                    this.RaisePropertyChanged("Msgerror");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="response_docs", Namespace="http://webservice.facturatech.co/")]
    [System.SerializableAttribute()]
    public partial class response_docs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string successField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgerrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string success {
            get {
                return this.successField;
            }
            set {
                if ((object.ReferenceEquals(this.successField, value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Msgerror {
            get {
                return this.MsgerrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgerrorField, value) != true)) {
                    this.MsgerrorField = value;
                    this.RaisePropertyChanged("Msgerror");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="response_xml", Namespace="http://webservice.facturatech.co/")]
    [System.SerializableAttribute()]
    public partial class response_xml : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string successField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resourceDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgerrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string success {
            get {
                return this.successField;
            }
            set {
                if ((object.ReferenceEquals(this.successField, value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string resourceData {
            get {
                return this.resourceDataField;
            }
            set {
                if ((object.ReferenceEquals(this.resourceDataField, value) != true)) {
                    this.resourceDataField = value;
                    this.RaisePropertyChanged("resourceData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Msgerror {
            get {
                return this.MsgerrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgerrorField, value) != true)) {
                    this.MsgerrorField = value;
                    this.RaisePropertyChanged("Msgerror");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="response_pdf", Namespace="http://webservice.facturatech.co/")]
    [System.SerializableAttribute()]
    public partial class response_pdf : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string successField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resourceDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgerrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string success {
            get {
                return this.successField;
            }
            set {
                if ((object.ReferenceEquals(this.successField, value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string resourceData {
            get {
                return this.resourceDataField;
            }
            set {
                if ((object.ReferenceEquals(this.resourceDataField, value) != true)) {
                    this.resourceDataField = value;
                    this.RaisePropertyChanged("resourceData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Msgerror {
            get {
                return this.MsgerrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgerrorField, value) != true)) {
                    this.MsgerrorField = value;
                    this.RaisePropertyChanged("Msgerror");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="response_cufe", Namespace="http://webservice.facturatech.co/")]
    [System.SerializableAttribute()]
    public partial class response_cufe : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string successField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resourceDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgerrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string success {
            get {
                return this.successField;
            }
            set {
                if ((object.ReferenceEquals(this.successField, value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string resourceData {
            get {
                return this.resourceDataField;
            }
            set {
                if ((object.ReferenceEquals(this.resourceDataField, value) != true)) {
                    this.resourceDataField = value;
                    this.RaisePropertyChanged("resourceData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Msgerror {
            get {
                return this.MsgerrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgerrorField, value) != true)) {
                    this.MsgerrorField = value;
                    this.RaisePropertyChanged("Msgerror");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="response_qr", Namespace="http://webservice.facturatech.co/")]
    [System.SerializableAttribute()]
    public partial class response_qr : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string successField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resourceDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgerrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string success {
            get {
                return this.successField;
            }
            set {
                if ((object.ReferenceEquals(this.successField, value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string resourceData {
            get {
                return this.resourceDataField;
            }
            set {
                if ((object.ReferenceEquals(this.resourceDataField, value) != true)) {
                    this.resourceDataField = value;
                    this.RaisePropertyChanged("resourceData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Msgerror {
            get {
                return this.MsgerrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgerrorField, value) != true)) {
                    this.MsgerrorField = value;
                    this.RaisePropertyChanged("Msgerror");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="response_qr_image_file", Namespace="http://webservice.facturatech.co/")]
    [System.SerializableAttribute()]
    public partial class response_qr_image_file : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string successField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resourceDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgerrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string success {
            get {
                return this.successField;
            }
            set {
                if ((object.ReferenceEquals(this.successField, value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string resourceData {
            get {
                return this.resourceDataField;
            }
            set {
                if ((object.ReferenceEquals(this.resourceDataField, value) != true)) {
                    this.resourceDataField = value;
                    this.RaisePropertyChanged("resourceData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Msgerror {
            get {
                return this.MsgerrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgerrorField, value) != true)) {
                    this.MsgerrorField = value;
                    this.RaisePropertyChanged("Msgerror");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.facturatech.co/", ConfigurationName="WSFTECHPRO.WSV2PROSoap")]
    public interface WSV2PROSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://webservice.facturatech.co/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/uploadInvoiceFile", ReplyAction="*")]
        WSFTechSoapPro.WSFTECHPRO.uploadInvoiceFileResponse uploadInvoiceFile(WSFTechSoapPro.WSFTECHPRO.uploadInvoiceFileRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://webservice.facturatech.co/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/uploadInvoiceFileLayout", ReplyAction="*")]
        WSFTechSoapPro.WSFTECHPRO.uploadInvoiceFileLayoutResponse uploadInvoiceFileLayout(WSFTechSoapPro.WSFTECHPRO.uploadInvoiceFileLayoutRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://webservice.facturatech.co/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/documentStatusFile", ReplyAction="*")]
        WSFTechSoapPro.WSFTECHPRO.documentStatusFileResponse documentStatusFile(WSFTechSoapPro.WSFTECHPRO.documentStatusFileRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://webservice.facturatech.co/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/downloadXMLFile", ReplyAction="*")]
        WSFTechSoapPro.WSFTECHPRO.downloadXMLFileResponse downloadXMLFile(WSFTechSoapPro.WSFTECHPRO.downloadXMLFileRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://webservice.facturatech.co/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/downloadPDFFile", ReplyAction="*")]
        WSFTechSoapPro.WSFTECHPRO.downloadPDFFileResponse downloadPDFFile(WSFTechSoapPro.WSFTECHPRO.downloadPDFFileRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://webservice.facturatech.co/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/downloadCUFEFile", ReplyAction="*")]
        WSFTechSoapPro.WSFTECHPRO.downloadCUFEFileResponse downloadCUFEFile(WSFTechSoapPro.WSFTECHPRO.downloadCUFEFileRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://webservice.facturatech.co/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/downloadQRFile", ReplyAction="*")]
        WSFTechSoapPro.WSFTECHPRO.downloadQRFileResponse downloadQRFile(WSFTechSoapPro.WSFTECHPRO.downloadQRFileRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://webservice.facturatech.co/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/downloadQRImageFile", ReplyAction="*")]
        WSFTechSoapPro.WSFTECHPRO.downloadQRImageFileResponse downloadQRImageFile(WSFTechSoapPro.WSFTECHPRO.downloadQRImageFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadInvoiceFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="uploadInvoiceFile", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapPro.WSFTECHPRO.uploadInvoiceFileRequestBody Body;
        
        public uploadInvoiceFileRequest() {
        }
        
        public uploadInvoiceFileRequest(WSFTechSoapPro.WSFTECHPRO.uploadInvoiceFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class uploadInvoiceFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xmlBase64;
        
        public uploadInvoiceFileRequestBody() {
        }
        
        public uploadInvoiceFileRequestBody(string username, string password, string xmlBase64) {
            this.username = username;
            this.password = password;
            this.xmlBase64 = xmlBase64;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadInvoiceFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="uploadInvoiceFileResponse", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapPro.WSFTECHPRO.uploadInvoiceFileResponseBody Body;
        
        public uploadInvoiceFileResponse() {
        }
        
        public uploadInvoiceFileResponse(WSFTechSoapPro.WSFTECHPRO.uploadInvoiceFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class uploadInvoiceFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSFTechSoapPro.WSFTECHPRO.response_ws uploadInvoiceFileResult;
        
        public uploadInvoiceFileResponseBody() {
        }
        
        public uploadInvoiceFileResponseBody(WSFTechSoapPro.WSFTECHPRO.response_ws uploadInvoiceFileResult) {
            this.uploadInvoiceFileResult = uploadInvoiceFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadInvoiceFileLayoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="uploadInvoiceFileLayout", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapPro.WSFTECHPRO.uploadInvoiceFileLayoutRequestBody Body;
        
        public uploadInvoiceFileLayoutRequest() {
        }
        
        public uploadInvoiceFileLayoutRequest(WSFTechSoapPro.WSFTECHPRO.uploadInvoiceFileLayoutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class uploadInvoiceFileLayoutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xmlBase64;
        
        public uploadInvoiceFileLayoutRequestBody() {
        }
        
        public uploadInvoiceFileLayoutRequestBody(string username, string password, string xmlBase64) {
            this.username = username;
            this.password = password;
            this.xmlBase64 = xmlBase64;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadInvoiceFileLayoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="uploadInvoiceFileLayoutResponse", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapPro.WSFTECHPRO.uploadInvoiceFileLayoutResponseBody Body;
        
        public uploadInvoiceFileLayoutResponse() {
        }
        
        public uploadInvoiceFileLayoutResponse(WSFTechSoapPro.WSFTECHPRO.uploadInvoiceFileLayoutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class uploadInvoiceFileLayoutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSFTechSoapPro.WSFTECHPRO.response_ws uploadInvoiceFileLayoutResult;
        
        public uploadInvoiceFileLayoutResponseBody() {
        }
        
        public uploadInvoiceFileLayoutResponseBody(WSFTechSoapPro.WSFTECHPRO.response_ws uploadInvoiceFileLayoutResult) {
            this.uploadInvoiceFileLayoutResult = uploadInvoiceFileLayoutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class documentStatusFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="documentStatusFile", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapPro.WSFTECHPRO.documentStatusFileRequestBody Body;
        
        public documentStatusFileRequest() {
        }
        
        public documentStatusFileRequest(WSFTechSoapPro.WSFTECHPRO.documentStatusFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class documentStatusFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string transaccionID;
        
        public documentStatusFileRequestBody() {
        }
        
        public documentStatusFileRequestBody(string username, string password, string transaccionID) {
            this.username = username;
            this.password = password;
            this.transaccionID = transaccionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class documentStatusFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="documentStatusFileResponse", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapPro.WSFTECHPRO.documentStatusFileResponseBody Body;
        
        public documentStatusFileResponse() {
        }
        
        public documentStatusFileResponse(WSFTechSoapPro.WSFTECHPRO.documentStatusFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class documentStatusFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSFTechSoapPro.WSFTECHPRO.response_docs documentStatusFileResult;
        
        public documentStatusFileResponseBody() {
        }
        
        public documentStatusFileResponseBody(WSFTechSoapPro.WSFTECHPRO.response_docs documentStatusFileResult) {
            this.documentStatusFileResult = documentStatusFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadXMLFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadXMLFile", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapPro.WSFTECHPRO.downloadXMLFileRequestBody Body;
        
        public downloadXMLFileRequest() {
        }
        
        public downloadXMLFileRequest(WSFTechSoapPro.WSFTECHPRO.downloadXMLFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class downloadXMLFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prefijo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string folio;
        
        public downloadXMLFileRequestBody() {
        }
        
        public downloadXMLFileRequestBody(string username, string password, string prefijo, string folio) {
            this.username = username;
            this.password = password;
            this.prefijo = prefijo;
            this.folio = folio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadXMLFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadXMLFileResponse", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapPro.WSFTECHPRO.downloadXMLFileResponseBody Body;
        
        public downloadXMLFileResponse() {
        }
        
        public downloadXMLFileResponse(WSFTechSoapPro.WSFTECHPRO.downloadXMLFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class downloadXMLFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSFTechSoapPro.WSFTECHPRO.response_xml downloadXMLFileResult;
        
        public downloadXMLFileResponseBody() {
        }
        
        public downloadXMLFileResponseBody(WSFTechSoapPro.WSFTECHPRO.response_xml downloadXMLFileResult) {
            this.downloadXMLFileResult = downloadXMLFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadPDFFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadPDFFile", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapPro.WSFTECHPRO.downloadPDFFileRequestBody Body;
        
        public downloadPDFFileRequest() {
        }
        
        public downloadPDFFileRequest(WSFTechSoapPro.WSFTECHPRO.downloadPDFFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class downloadPDFFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prefijo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string folio;
        
        public downloadPDFFileRequestBody() {
        }
        
        public downloadPDFFileRequestBody(string username, string password, string prefijo, string folio) {
            this.username = username;
            this.password = password;
            this.prefijo = prefijo;
            this.folio = folio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadPDFFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadPDFFileResponse", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapPro.WSFTECHPRO.downloadPDFFileResponseBody Body;
        
        public downloadPDFFileResponse() {
        }
        
        public downloadPDFFileResponse(WSFTechSoapPro.WSFTECHPRO.downloadPDFFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class downloadPDFFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSFTechSoapPro.WSFTECHPRO.response_pdf downloadPDFFileResult;
        
        public downloadPDFFileResponseBody() {
        }
        
        public downloadPDFFileResponseBody(WSFTechSoapPro.WSFTECHPRO.response_pdf downloadPDFFileResult) {
            this.downloadPDFFileResult = downloadPDFFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadCUFEFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadCUFEFile", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapPro.WSFTECHPRO.downloadCUFEFileRequestBody Body;
        
        public downloadCUFEFileRequest() {
        }
        
        public downloadCUFEFileRequest(WSFTechSoapPro.WSFTECHPRO.downloadCUFEFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class downloadCUFEFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prefijo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string folio;
        
        public downloadCUFEFileRequestBody() {
        }
        
        public downloadCUFEFileRequestBody(string username, string password, string prefijo, string folio) {
            this.username = username;
            this.password = password;
            this.prefijo = prefijo;
            this.folio = folio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadCUFEFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadCUFEFileResponse", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapPro.WSFTECHPRO.downloadCUFEFileResponseBody Body;
        
        public downloadCUFEFileResponse() {
        }
        
        public downloadCUFEFileResponse(WSFTechSoapPro.WSFTECHPRO.downloadCUFEFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class downloadCUFEFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSFTechSoapPro.WSFTECHPRO.response_cufe downloadCUFEFileResult;
        
        public downloadCUFEFileResponseBody() {
        }
        
        public downloadCUFEFileResponseBody(WSFTechSoapPro.WSFTECHPRO.response_cufe downloadCUFEFileResult) {
            this.downloadCUFEFileResult = downloadCUFEFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadQRFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadQRFile", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapPro.WSFTECHPRO.downloadQRFileRequestBody Body;
        
        public downloadQRFileRequest() {
        }
        
        public downloadQRFileRequest(WSFTechSoapPro.WSFTECHPRO.downloadQRFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class downloadQRFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prefijo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string folio;
        
        public downloadQRFileRequestBody() {
        }
        
        public downloadQRFileRequestBody(string username, string password, string prefijo, string folio) {
            this.username = username;
            this.password = password;
            this.prefijo = prefijo;
            this.folio = folio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadQRFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadQRFileResponse", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapPro.WSFTECHPRO.downloadQRFileResponseBody Body;
        
        public downloadQRFileResponse() {
        }
        
        public downloadQRFileResponse(WSFTechSoapPro.WSFTECHPRO.downloadQRFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class downloadQRFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSFTechSoapPro.WSFTECHPRO.response_qr downloadQRFileResult;
        
        public downloadQRFileResponseBody() {
        }
        
        public downloadQRFileResponseBody(WSFTechSoapPro.WSFTECHPRO.response_qr downloadQRFileResult) {
            this.downloadQRFileResult = downloadQRFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadQRImageFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadQRImageFile", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapPro.WSFTECHPRO.downloadQRImageFileRequestBody Body;
        
        public downloadQRImageFileRequest() {
        }
        
        public downloadQRImageFileRequest(WSFTechSoapPro.WSFTECHPRO.downloadQRImageFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class downloadQRImageFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prefijo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string folio;
        
        public downloadQRImageFileRequestBody() {
        }
        
        public downloadQRImageFileRequestBody(string username, string password, string prefijo, string folio) {
            this.username = username;
            this.password = password;
            this.prefijo = prefijo;
            this.folio = folio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadQRImageFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadQRImageFileResponse", Namespace="http://webservice.facturatech.co/", Order=0)]
        public WSFTechSoapPro.WSFTECHPRO.downloadQRImageFileResponseBody Body;
        
        public downloadQRImageFileResponse() {
        }
        
        public downloadQRImageFileResponse(WSFTechSoapPro.WSFTECHPRO.downloadQRImageFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class downloadQRImageFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSFTechSoapPro.WSFTECHPRO.response_qr_image_file downloadQRImageFileResult;
        
        public downloadQRImageFileResponseBody() {
        }
        
        public downloadQRImageFileResponseBody(WSFTechSoapPro.WSFTECHPRO.response_qr_image_file downloadQRImageFileResult) {
            this.downloadQRImageFileResult = downloadQRImageFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSV2PROSoapChannel : WSFTechSoapPro.WSFTECHPRO.WSV2PROSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSV2PROSoapClient : System.ServiceModel.ClientBase<WSFTechSoapPro.WSFTECHPRO.WSV2PROSoap>, WSFTechSoapPro.WSFTECHPRO.WSV2PROSoap {
        
        public WSV2PROSoapClient() {
        }
        
        public WSV2PROSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSV2PROSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSV2PROSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSV2PROSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFTechSoapPro.WSFTECHPRO.uploadInvoiceFileResponse WSFTechSoapPro.WSFTECHPRO.WSV2PROSoap.uploadInvoiceFile(WSFTechSoapPro.WSFTECHPRO.uploadInvoiceFileRequest request) {
            return base.Channel.uploadInvoiceFile(request);
        }
        
        public WSFTechSoapPro.WSFTECHPRO.response_ws uploadInvoiceFile(string username, string password, string xmlBase64) {
            WSFTechSoapPro.WSFTECHPRO.uploadInvoiceFileRequest inValue = new WSFTechSoapPro.WSFTECHPRO.uploadInvoiceFileRequest();
            inValue.Body = new WSFTechSoapPro.WSFTECHPRO.uploadInvoiceFileRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.xmlBase64 = xmlBase64;
            WSFTechSoapPro.WSFTECHPRO.uploadInvoiceFileResponse retVal = ((WSFTechSoapPro.WSFTECHPRO.WSV2PROSoap)(this)).uploadInvoiceFile(inValue);
            return retVal.Body.uploadInvoiceFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFTechSoapPro.WSFTECHPRO.uploadInvoiceFileLayoutResponse WSFTechSoapPro.WSFTECHPRO.WSV2PROSoap.uploadInvoiceFileLayout(WSFTechSoapPro.WSFTECHPRO.uploadInvoiceFileLayoutRequest request) {
            return base.Channel.uploadInvoiceFileLayout(request);
        }
        
        public WSFTechSoapPro.WSFTECHPRO.response_ws uploadInvoiceFileLayout(string username, string password, string xmlBase64) {
            WSFTechSoapPro.WSFTECHPRO.uploadInvoiceFileLayoutRequest inValue = new WSFTechSoapPro.WSFTECHPRO.uploadInvoiceFileLayoutRequest();
            inValue.Body = new WSFTechSoapPro.WSFTECHPRO.uploadInvoiceFileLayoutRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.xmlBase64 = xmlBase64;
            WSFTechSoapPro.WSFTECHPRO.uploadInvoiceFileLayoutResponse retVal = ((WSFTechSoapPro.WSFTECHPRO.WSV2PROSoap)(this)).uploadInvoiceFileLayout(inValue);
            return retVal.Body.uploadInvoiceFileLayoutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFTechSoapPro.WSFTECHPRO.documentStatusFileResponse WSFTechSoapPro.WSFTECHPRO.WSV2PROSoap.documentStatusFile(WSFTechSoapPro.WSFTECHPRO.documentStatusFileRequest request) {
            return base.Channel.documentStatusFile(request);
        }
        
        public WSFTechSoapPro.WSFTECHPRO.response_docs documentStatusFile(string username, string password, string transaccionID) {
            WSFTechSoapPro.WSFTECHPRO.documentStatusFileRequest inValue = new WSFTechSoapPro.WSFTECHPRO.documentStatusFileRequest();
            inValue.Body = new WSFTechSoapPro.WSFTECHPRO.documentStatusFileRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.transaccionID = transaccionID;
            WSFTechSoapPro.WSFTECHPRO.documentStatusFileResponse retVal = ((WSFTechSoapPro.WSFTECHPRO.WSV2PROSoap)(this)).documentStatusFile(inValue);
            return retVal.Body.documentStatusFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFTechSoapPro.WSFTECHPRO.downloadXMLFileResponse WSFTechSoapPro.WSFTECHPRO.WSV2PROSoap.downloadXMLFile(WSFTechSoapPro.WSFTECHPRO.downloadXMLFileRequest request) {
            return base.Channel.downloadXMLFile(request);
        }
        
        public WSFTechSoapPro.WSFTECHPRO.response_xml downloadXMLFile(string username, string password, string prefijo, string folio) {
            WSFTechSoapPro.WSFTECHPRO.downloadXMLFileRequest inValue = new WSFTechSoapPro.WSFTECHPRO.downloadXMLFileRequest();
            inValue.Body = new WSFTechSoapPro.WSFTECHPRO.downloadXMLFileRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.prefijo = prefijo;
            inValue.Body.folio = folio;
            WSFTechSoapPro.WSFTECHPRO.downloadXMLFileResponse retVal = ((WSFTechSoapPro.WSFTECHPRO.WSV2PROSoap)(this)).downloadXMLFile(inValue);
            return retVal.Body.downloadXMLFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFTechSoapPro.WSFTECHPRO.downloadPDFFileResponse WSFTechSoapPro.WSFTECHPRO.WSV2PROSoap.downloadPDFFile(WSFTechSoapPro.WSFTECHPRO.downloadPDFFileRequest request) {
            return base.Channel.downloadPDFFile(request);
        }
        
        public WSFTechSoapPro.WSFTECHPRO.response_pdf downloadPDFFile(string username, string password, string prefijo, string folio) {
            WSFTechSoapPro.WSFTECHPRO.downloadPDFFileRequest inValue = new WSFTechSoapPro.WSFTECHPRO.downloadPDFFileRequest();
            inValue.Body = new WSFTechSoapPro.WSFTECHPRO.downloadPDFFileRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.prefijo = prefijo;
            inValue.Body.folio = folio;
            WSFTechSoapPro.WSFTECHPRO.downloadPDFFileResponse retVal = ((WSFTechSoapPro.WSFTECHPRO.WSV2PROSoap)(this)).downloadPDFFile(inValue);
            return retVal.Body.downloadPDFFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFTechSoapPro.WSFTECHPRO.downloadCUFEFileResponse WSFTechSoapPro.WSFTECHPRO.WSV2PROSoap.downloadCUFEFile(WSFTechSoapPro.WSFTECHPRO.downloadCUFEFileRequest request) {
            return base.Channel.downloadCUFEFile(request);
        }
        
        public WSFTechSoapPro.WSFTECHPRO.response_cufe downloadCUFEFile(string username, string password, string prefijo, string folio) {
            WSFTechSoapPro.WSFTECHPRO.downloadCUFEFileRequest inValue = new WSFTechSoapPro.WSFTECHPRO.downloadCUFEFileRequest();
            inValue.Body = new WSFTechSoapPro.WSFTECHPRO.downloadCUFEFileRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.prefijo = prefijo;
            inValue.Body.folio = folio;
            WSFTechSoapPro.WSFTECHPRO.downloadCUFEFileResponse retVal = ((WSFTechSoapPro.WSFTECHPRO.WSV2PROSoap)(this)).downloadCUFEFile(inValue);
            return retVal.Body.downloadCUFEFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFTechSoapPro.WSFTECHPRO.downloadQRFileResponse WSFTechSoapPro.WSFTECHPRO.WSV2PROSoap.downloadQRFile(WSFTechSoapPro.WSFTECHPRO.downloadQRFileRequest request) {
            return base.Channel.downloadQRFile(request);
        }
        
        public WSFTechSoapPro.WSFTECHPRO.response_qr downloadQRFile(string username, string password, string prefijo, string folio) {
            WSFTechSoapPro.WSFTECHPRO.downloadQRFileRequest inValue = new WSFTechSoapPro.WSFTECHPRO.downloadQRFileRequest();
            inValue.Body = new WSFTechSoapPro.WSFTECHPRO.downloadQRFileRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.prefijo = prefijo;
            inValue.Body.folio = folio;
            WSFTechSoapPro.WSFTECHPRO.downloadQRFileResponse retVal = ((WSFTechSoapPro.WSFTECHPRO.WSV2PROSoap)(this)).downloadQRFile(inValue);
            return retVal.Body.downloadQRFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSFTechSoapPro.WSFTECHPRO.downloadQRImageFileResponse WSFTechSoapPro.WSFTECHPRO.WSV2PROSoap.downloadQRImageFile(WSFTechSoapPro.WSFTECHPRO.downloadQRImageFileRequest request) {
            return base.Channel.downloadQRImageFile(request);
        }
        
        public WSFTechSoapPro.WSFTECHPRO.response_qr_image_file downloadQRImageFile(string username, string password, string prefijo, string folio) {
            WSFTechSoapPro.WSFTECHPRO.downloadQRImageFileRequest inValue = new WSFTechSoapPro.WSFTECHPRO.downloadQRImageFileRequest();
            inValue.Body = new WSFTechSoapPro.WSFTECHPRO.downloadQRImageFileRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.prefijo = prefijo;
            inValue.Body.folio = folio;
            WSFTechSoapPro.WSFTECHPRO.downloadQRImageFileResponse retVal = ((WSFTechSoapPro.WSFTECHPRO.WSV2PROSoap)(this)).downloadQRImageFile(inValue);
            return retVal.Body.downloadQRImageFileResult;
        }
    }
}
